In [1]:
# importing pandas package 
import pandas as pd 
# making data frame from csv file 
data = pd.read_csv("C:/delete/importCSV/SeattleCrime-GroupRobot-RemoveDuplicatesTest.csv")

In [2]:
data

,Offense Type,Offense Description,Report Date,Offense Start Date,Offense End Date,Block,District,Beat,2000 Census Tract,Longitude,Latitude
0,VEH-THEFT-AUTO,VEHICLE THEFT,2016-08-22 10:20:00,2016-08-21 22:30:00,2016-08-22 09:00:00,7XX BLOCK OF NW 58 ST,B,B2,3400.3006,-122.365631,47.670891
1,THEFT-LICENSE PLATE,OTHER PROPERTY,2016-08-27 17:25:00,2016-08-26 15:30:00,2016-08-27 15:00:00,18XX BLOCK OF 36 AV W,Q,Q1,5600.3037,-122.403702,47.635548
2,ASSLT-AGG-GUN,ASSAULT,2016-08-28 01:25:00,2016-08-28 01:25:00,NaN,5XX BLOCK OF 2 AV,K,K2,8100.1057,-122.332253,47.602013
3,THEFT-LICENSE PLATE,OTHER PROPERTY,2016-08-28 10:24:00,2016-08-27 21:30:00,2016-08-28 09:30:00,7XX BLOCK OF 35 AV,G,G2,7800.2026,-122.288322,47.608585
4,TRAFFIC,TRAFFIC,2016-08-28 02:14:00,2016-08-28 02:14:00,NaN,11 AV / E HOWELL ST,E,E2,7500.4001,-122.318199,47.617592
...,...,...,...,...,...,...,...,...,...,...,...
636265,DISTURBANCE-OTH,DISTURBANCE,2014-01-18 04:09:00,2014-01-18 02:57:00,NaN,14XX BLOCK OF BROADWAY,E,E2,8400.1008,-122.320770,47.613518
636266,THEFT-OTH,OTHER PROPERTY,2014-01-16 20:24:00,2014-01-16 13:00:00,2014-01-16 14:00:00,BOREN AV / VIRGINIA ST,D,D2,7300.2022,-122.334023,47.617710
636267,THEFT-MAIL,MAIL THEFT,2014-01-17 13:23:00,2013-12-17 00:00:00,2014-01-01 23:59:00,17XX BLOCK OF E JOHN ST,C,C2,7600.3012,-122.309410,47.619671
636268,FRAUD-CHECK,FRAUD,2014-01-17 13:59:00,2014-01-02 00:00:00,2014-01-02 23:59:00,19XX BLOCK OF WESTLAKE AV,M,M2,7300.3027,-122.337654,47.614388
636269,THEFT-OTH,OTHER PROPERTY,2014-01-17 14:15:00,2013-11-25 09:00:00,2014-01-17 14:15:00,4XX BLOCK OF PIKE ST,M,M3,8100.2005,-122.336128,47.610447

In [3]:
data = data.astype({'Longitude': 'float64', 'Latitude': 'float64', '2000 Census Tract': 'object'})
# data = data.astype({'Longitude': 'object', 'Latitude': 'object', '2000 Census Tract': 'object'})

In [4]:
# data.applymap(lambda x: x.strip() if isinstance(x, str) else x)

In [5]:
data = data.round(5)
# data

In [6]:
# sorting by first name 
# data.sort_values(by=['Offense Start Date', 'Longitude', 'Latitude'], inplace = True) 

# dropping ALL duplicte values 
data.drop_duplicates(subset=['Offense Start Date', 'Longitude', 'Latitude'], 
                     keep = 'first', inplace = True) 
  
# displaying data 
data

,Offense Type,Offense Description,Report Date,Offense Start Date,Offense End Date,Block,District,Beat,2000 Census Tract,Longitude,Latitude
0,VEH-THEFT-AUTO,VEHICLE THEFT,2016-08-22 10:20:00,2016-08-21 22:30:00,2016-08-22 09:00:00,7XX BLOCK OF NW 58 ST,B,B2,3400.3,-122.36563,47.67089
1,THEFT-LICENSE PLATE,OTHER PROPERTY,2016-08-27 17:25:00,2016-08-26 15:30:00,2016-08-27 15:00:00,18XX BLOCK OF 36 AV W,Q,Q1,5600.3,-122.40370,47.63555
2,ASSLT-AGG-GUN,ASSAULT,2016-08-28 01:25:00,2016-08-28 01:25:00,NaN,5XX BLOCK OF 2 AV,K,K2,8100.11,-122.33225,47.60201
3,THEFT-LICENSE PLATE,OTHER PROPERTY,2016-08-28 10:24:00,2016-08-27 21:30:00,2016-08-28 09:30:00,7XX BLOCK OF 35 AV,G,G2,7800.2,-122.28832,47.60859
4,TRAFFIC,TRAFFIC,2016-08-28 02:14:00,2016-08-28 02:14:00,NaN,11 AV / E HOWELL ST,E,E2,7500.4,-122.31820,47.61759
...,...,...,...,...,...,...,...,...,...,...,...
636254,OBSTRUCT,OBSTRUCT,2016-05-21 22:53:00,2016-05-21 22:39:00,NaN,12 AV / E PIKE ST,E,E2,7500.4,-122.31683,47.61411
636255,TRESPASS,TRESPASS,2016-05-23 23:17:00,2016-05-23 23:17:00,NaN,5XX BLOCK OF NORTHGATE ML,L,L2,1200.4,-122.32586,47.70609
636256,THEFT-CARPROWL,CAR PROWL,2016-01-29 07:55:00,2016-01-28 18:30:00,NaN,2 AV / VIRGINIA ST,M,M1,8002.1,-122.34176,47.61173
636257,THEFT-BICYCLE,BIKE THEFT,2016-02-22 10:30:00,2016-02-22 10:30:00,NaN,8XX BLOCK OF HIAWATHA PL S,G,G3,9400.2,-122.30967,47.59515
636258,THREATS-KILL,THREATS,2014-02-03 10:30:00,2014-02-03 06:50:00,NaN,3XX BLOCK OF 23 AV S,G,G3,8900.3,-122.30224,47.59980

In [7]:
data.dtypes

Offense Type            object
Offense Description     object
Report Date             object
Offense Start Date      object
Offense End Date        object
Block                   object
District                object
Beat                    object
2000 Census Tract       object
Longitude              float64
Latitude               float64
dtype: object

In [8]:
data.to_csv('C:/delete/importCSV/SeattleCrime-GroupRobot-RemoveDuplicates_pandas.csv',index=False)